### ISSUE TITLE
Sql error. 'password_reset_token' has no default value on signup.

### ISSUE THREAD

**Issue by Stasgar** [samdark/yiipowered#1]
Migration sets empty value to user's 'password_reset_token' cell in db.
It causes a Database Exception on signup:

> SQLSTATE[HY000]: General error: 1364 Field 'password_reset_token' doesn't have a default value

Fix for migration:
`'password_reset_token' => $this->string();`

**Comment by samdark** [comment]
Yes, should be generated at signup...
