### ISSUE TITLE
Professional design

### ISSUE THREAD

**Issue by samdark** [samdark/yiipowered#21]
Current design is a standard bootstrap template plus some effort by myself. It's not really good so if you can contribute professionally on this matter, please comment.

**Comment by githubjeka** [comment]
For first time you could change default black/white bootstrap to [free theme](https://bootswatch.com/slate/#navbar)
File is https://bootswatch.com/slate/bootstrap.css


![image](https://cloud.githubusercontent.com/assets/874234/23447448/1c9f6230-fe5c-11e6-9a08-22243a405fc1.png)

Not terrible as standard.

**Comment by HashemKhalifa** [comment]
Yes, I can :)

**Comment by samdark** [comment]
Worked on by designer. Mocks will be published here after they're finished.

**Comment by HashemKhalifa** [comment]
Waiting..
@devypt

**Comment by sokoji** [comment]
What about this issue?
Does anybody work on it?

**Comment by samdark** [comment]
Yes. @SilverFire is on it.

**Comment by SilverFire** [comment]
Here is what we have

![home page web_2 6](https://cloud.githubusercontent.com/assets/4499203/25775564/a3e2ae4a-32b0-11e7-99c0-c33720f3de5d.png)

![project page web](https://cloud.githubusercontent.com/assets/4499203/25775567/b30b1c5e-32b0-11e7-9241-562cc9bb2c47.png)
