### ISSUE TITLE
Выравнивание элементов по сетке

### ISSUE THREAD

**Issue by lex111** [samdark/yiipowered#27]
Заголовки и ссылка "Показать ещё" смещены влево, что довольно заметно и несколько "режет" глаз. Хотел предложить исправление, но предварительно перед этим посмотреть историю коммитов, и увидел что так было сделано [намерено](https://github.com/samdark/yiipowered/commit/e93f7547f109c2c2c4ffe0f59d8c779be4d7de02), но для чего, ведь так быть не должно?

![1488663165140](https://cloud.githubusercontent.com/assets/4408379/23582450/59d4a822-013b-11e7-82fe-5af0aef1540b.jpg)

**Comment by samdark** [comment]
Да, можно и поправить... не помню, зачем так сделал...
