### ISSUE TITLE
The minimum requirement >= PHP 7, it's not >= PHP 5.4

### ISSUE THREAD

**Issue by maxomato** [samdark/yiipowered#41]
I tried to build this project with composer and I got these errors.

 Problem 1
    - Installation request for claviska/simpleimage 3.3.1 -> satisfiable by claviska/simpleimage[3.3.1].
    - claviska/simpleimage 3.3.1 requires php >=5.6.0 -> your PHP version (5.5.9) does not satisfy that requirement.

After I had  installed php 5.6, the project built but on start this error occured

![image](https://cloud.githubusercontent.com/assets/17249758/26495284/baaf32b2-422b-11e7-980b-51875c101dc6.png)

I checked that php construction 
(clone $newProvider->query)->limit(null) is supported from php7

**Comment by samdark** [comment]
Yes, indeed. Do you want to work with the project using 5.6 so I'll fix it or is it OK to bump requirements to PHP 7 to reflect current state of things?

**Comment by maxomato** [comment]
OK, PHP 7 will be good for me too.

**Comment by samdark** [comment]
Done.
