### ISSUE TITLE
Screenshot size

### ISSUE THREAD

**Issue by bigbrush** [samdark/yiipowered#43]
Please add image dimension for screenshots in the description of the upload screen.

**Comment by samdark** [comment]
It doesn't matter since it offers to resize afterwards.

**Comment by bigbrush** [comment]
Fine by me .... But. I didn't manage to provide images where the resizing allowed me to display the full image (which is apparent on the screen shots for BIG Cms).

**Comment by samdark** [comment]
Right. I've got it now. What you're asking for is aspect ratio, not resolution.

**Comment by bigbrush** [comment]
Yup, that is what i mean :)

**Comment by samdark** [comment]
Since there's now abiltiy to automatically get the screenshot, it is no longer a critical thing.
