### ISSUE TITLE
Удаление профиля пользователя

### ISSUE THREAD

**Issue by s1lver** [samdark/yiipowered#55]
Доброго времени суток!

Есть ли сейчас возможность удаления профиля пользователя? Если такой возможности нет, то может стоит добавить?

**Comment by samdark** [comment]
Возможности нет. Пока никто не спрашивал. Хочется самоудалиться? :)

**Comment by s1lver** [comment]
Пока нет, но кто знает может захочется.

**Comment by samdark** [comment]
Decided not to implement it.
