### ISSUE TITLE
Automate website screenshots

### ISSUE THREAD

**Issue by brussens** [samdark/yiipowered#6]
The idea is to create a bot that would visit websites and take screenshots automatically.

---

@samdark вот думаю написать расширение для создания скриншотов для проектов, что думаете? Работать будет через API стороннего сервиса. Как считаете, пригодится?

**Comment by samdark** [comment]
Может и пригодится.

**Comment by dignityinside** [comment]
+1

**Comment by samdark** [comment]
Попробовал https://www.s-shot.ru/. Не пойдёт. В некоторых случаях дико глючит.

**Comment by b17** [comment]
@samdark https://phantomjscloud.com/

**Comment by brussens** [comment]
@b17 там только 500 скриншотов можно сделать вроде как.

**Comment by bigbrush** [comment]
english please

**Comment by samdark** [comment]
@bigbrush description and title updated.

**Comment by samdark** [comment]
https://github.com/spatie/browsershot

**Comment by samdark** [comment]
https://github.com/graphcool/chromeless

**Comment by jakim** [comment]
screenshotlayer.com
100 free screenshots per month. It's probably more than enough for now.

**Comment by samdark** [comment]
Done. Missing screenshots are now fetched every night.
