### ISSUE TITLE
Layout issue on project view page

### ISSUE THREAD

**Issue by SilverFire** [samdark/yiipowered#62]
![image](https://user-images.githubusercontent.com/4499203/36265991-297d3ec8-1279-11e8-8b27-0214c11f5d10.png)

http://yiipowered.com/en/projects/453/logistics-chain-system

**Comment by prodex** [comment]
Second photo added via description. I think need to remove the possibility of adding images to the description.

**Comment by samdark** [comment]
That's a good idea.

**Comment by samdark** [comment]
Could be done by configuring HTMLPurifier.
