### ISSUE TITLE
Can not log in with github

### ISSUE THREAD

**Issue by rugabarbo** [samdark/yiipowered#66]
Received an error:

`Unable to save user: {"notify_about_comment_on_email":["Notify about new comments by e-mail cannot be blank."]}`

![18 03 03-16 48 09](https://user-images.githubusercontent.com/6429469/36935003-b0fc01b4-1f02-11e8-8097-5ac7e4199e57.jpg)

**Comment by samdark** [comment]
That's your first time login, right?

**Comment by rugabarbo** [comment]
Yes.

**Comment by samdark** [comment]
Should be something around https://github.com/samdark/yiipowered/blob/master/components/AuthHandler.php#L68

**Comment by rugabarbo** [comment]
Yes, it's OK now.
