### ISSUE TITLE
Проверка доступности

### ISSUE THREAD

**Issue by brussens** [samdark/yiipowered#7]
Может написать валидатор, который будет проверять доступность того или иного проекта?

**Comment by samdark** [comment]
Это лучше по крону делать и помечать недоступные проекты.

**Comment by brussens** [comment]
@samdark ну или так. Может реализовать?

**Comment by samdark** [comment]
В отдельной ветке можно, почему нет.

**Comment by samdark** [comment]
Decided not to implement it.
