### ISSUE TITLE
Show only "global" sites on english version

### ISSUE THREAD

**Issue by IStranger** [samdark/yiipowered#75]
It makes sense to hide all "local" projects from english version of site:
     https://yiipowered.com/en

It may look suspicious for americans or europeans. They will not understand screenshots with cyrillic symbols.

**Comment by samdark** [comment]
Suspicious? I don't think so. Kinda useless — yes.

There's an ability to translate for a single language. I think, instead of removing, these could be translated.

**Comment by samdark** [comment]
Decided not to implement it.
