### ISSUE TITLE
Technology verification

### ISSUE THREAD

**Issue by samdark** [samdark/yiipowered#82]
See https://github.com/butteff/yiichecker. When it's verified that Yii is there, apply "verified" mark to the project.

**Comment by samdark** [comment]
Additional marks could be added for admin if it's detected as Wordpress.

**Comment by nedarta** [comment]
Hi. It's still relevant. I see a lot of websites to promote NFT, porn, market sales tools etc. As far as I took a look - most of them aren't Yii-based.

**Comment by samdark** [comment]
Yes, this is actual but I have no time to clean that up manually. A pull request with a command that checks websites and adds a flag like "likely not Yii" would be super-useful.

**Comment by samdark** [comment]
Decided to fiddle with it...

**Comment by samdark** [comment]
Partially done:

1. All website URLs are now checked.
2. Wordpress-powered pages are unpublished automatically.
3. Verified Yii projects are marked as such in database.
4. If there's a Yii version mismatch, it is fixed.

TODO:

- [ ] More validators for certainly non-Yii tech.
- [ ] Ability to mark project as verified manually to mark Yii-powered projects with non-Yii front pages as OK.

**Comment by samdark** [comment]
Done. Also cleaned up content.
